### PR TITLE
Updated the build tools version and added READ_EXTERNAL_STORAGE permission

### PR DESCRIPTION
**Pull request by heraldofsolace**
Updated the Build tools version 

Added READ_EXTERNAL_STORAGE permission. For some reason, it shows me the grant permission dialog two times- one after pressing "start" and another after pressing back.

### CODE REVIEW

**Comment by fennifith** [comment]
Thanks for your help! Could you remove the junk files (like local.properties and the entire .idea directory), then I'll approve the PR?

**Comment by heraldofsolace** [comment]
I managed to delete local.properties. How to I delete the .idea folder?

**Comment by heraldofsolace** [comment]
Nevermind, figure it out. Are they gone now?

**Comment by fennifith** [comment]
Ugh, there's also gradle.properties and the two .iml files :P

**Comment by heraldofsolace** [comment]
FML, this is my first time using github :-P They should be gone now.

**Comment by fennifith** [comment]
Okay yep, NOW it's good (that took a while) 😅

**Comment by heraldofsolace** [comment]
Thanks, they should teach git in school.

**Pull request merged**
